name: Build

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore .NET tools
      run: dotnet tool restore

    - name: Restore dependencies
      run: dotnet restore RemoCommander.slnx

    - name: Check code formatting
      run: dotnet format RemoCommander.slnx --verify-no-changes --verbosity diagnostic

    - name: Build solution
      run: dotnet build RemoCommander.slnx --no-restore -c Release

    - name: Test
      run: dotnet test RemoCommander.slnx --no-build -c Release --verbosity normal
